### ISSUE TITLE
Clicking Interpolate Button Throws an Error

### ISSUE THREAD

**Issue by hekuli** [DarienBrito/TDMorph#190]
Just discovered this component. Looks awesome, but 2 minutes into a fresh install I'm stuck with an error. Everytime I simply click the interpolate button I get the following error:

```
Traceback (most recent call last):
  File "/project1/generators/TDMorph/Container1/PanelContent/ElementsContainer/Menus/Randomize/Morph/panelexec1", line 8, in onOffToOn
  File "/project1/generators/TDMorph/Container1/PanelContent/ElementsContainer/Menus/Randomize/Morph/extTDMorphButton", line 57, in OffToOn
td.tdError: /project1/generators/TDMorph/Container1/PanelContent/ElementsContainer/PresetManager/PresetMorpher/extPresetMorpher:227: tdWarning: Expected locked operator, or execution within onCook method of a Script Operator.
  File "</project1/generators/TDMorph/Container1/PanelContent/ElementsContainer/Menus/Randomize/Morph:mod("../RandomizeScript").onInterpolate()>", line 1
  File "/project1/generators/TDMorph/Container1/PanelContent/ElementsContainer/Menus/Randomize/RandomizeScript", line 7, in onInterpolate
  File "/project1/generators/TDMorph/Container1/PanelContent/ElementsContainer/PresetManager/extUIExtension", line 208, in UIRandomMorph
  File "/project1/generators/TDMorph/Container1/PanelContent/ElementsContainer/PresetManager/PresetMorpher/extUIExtension", line 122, in RandomMorphWithStoredRanges
  File "/project1/generators/TDMorph/Container1/PanelContent/ElementsContainer/PresetManager/PresetMorpher/extPresetMorpher", line 228, in writeEssentialValues
  File "/project1/generators/TDMorph/Container1/PanelContent/ElementsContainer/PresetManager/PresetMorpher/extPresetMorpher", line 154, in setOriginalParameterProperties
td.tdError: Expected locked operator, or execution within onCook method of a Script Operator.
Results of run operation resulted in exception.
```

TDMorph 2.0
TD 2022.33910
Mac OS Ventura 13.4.1 (c) (22F770820d)

**Comment by DarienBrito** [comment]
TDMorph 2.0 is outdated, current one is 3.0. However, upcoming stable version is 3.1.0 please use latest version when released  (coming out very soon) :)
